import type { RadarCountry } from './live-osint-types';
export type AfricanCountry = RadarCountry & { gdeltCode: string };
export const AFRICAN_COUNTRIES: AfricanCountry[] = [
  { code: 'DZ', gdeltCode: 'AG', name: 'Algérie', region: 'Afrique du Nord', latitude: 28.0, longitude: 2.6 },
  { code: 'AO', gdeltCode: 'AO', name: 'Angola', region: 'Afrique centrale', latitude: -8.8, longitude: 13.2 },
  { code: 'BJ', gdeltCode: 'BN', name: 'Bénin', region: 'Afrique de l’Ouest', latitude: 6.5, longitude: 2.6 },
  { code: 'BW', gdeltCode: 'BC', name: 'Botswana', region: 'Afrique australe', latitude: -24.6, longitude: 25.9 },
  { code: 'BF', gdeltCode: 'UV', name: 'Burkina Faso', region: 'Afrique de l’Ouest', latitude: 12.4, longitude: -1.5 },
  { code: 'BI', gdeltCode: 'BY', name: 'Burundi', region: 'Afrique de l’Est', latitude: -3.4, longitude: 29.4 },
  { code: 'CV', gdeltCode: 'CV', name: 'Cap-Vert', region: 'Afrique de l’Ouest', latitude: 15.1, longitude: -23.6 },
  { code: 'CM', gdeltCode: 'CM', name: 'Cameroun', region: 'Afrique centrale', latitude: 3.9, longitude: 11.5 },
  { code: 'CF', gdeltCode: 'CT', name: 'République centrafricaine', region: 'Afrique centrale', latitude: 6.6, longitude: 20.9 },
  { code: 'TD', gdeltCode: 'CD', name: 'Tchad', region: 'Afrique centrale', latitude: 12.1, longitude: 15.0 },
  { code: 'KM', gdeltCode: 'CN', name: 'Comores', region: 'Afrique de l’Est', latitude: -11.7, longitude: 43.3 },
  { code: 'CG', gdeltCode: 'CF', name: 'République du Congo', region: 'Afrique centrale', latitude: -4.3, longitude: 15.3 },
  { code: 'CD', gdeltCode: 'CG', name: 'République démocratique du Congo', region: 'Afrique centrale', latitude: -2.8, longitude: 23.7 },
  { code: 'CI', gdeltCode: 'IV', name: 'Côte d’Ivoire', region: 'Afrique de l’Ouest', latitude: 5.3, longitude: -4.0 },
  { code: 'DJ', gdeltCode: 'DJ', name: 'Djibouti', region: 'Afrique de l’Est', latitude: 11.6, longitude: 43.1 },
  { code: 'EG', gdeltCode: 'EG', name: 'Égypte', region: 'Afrique du Nord', latitude: 26.8, longitude: 30.8 },
  { code: 'GQ', gdeltCode: 'EK', name: 'Guinée équatoriale', region: 'Afrique centrale', latitude: 1.7, longitude: 10.3 },
  { code: 'ER', gdeltCode: 'ER', name: 'Érythrée', region: 'Afrique de l’Est', latitude: 15.3, longitude: 38.9 },
  { code: 'SZ', gdeltCode: 'WZ', name: 'Eswatini', region: 'Afrique australe', latitude: -26.5, longitude: 31.5 },
  { code: 'ET', gdeltCode: 'ET', name: 'Éthiopie', region: 'Afrique de l’Est', latitude: 9.0, longitude: 38.8 },
  { code: 'GA', gdeltCode: 'GB', name: 'Gabon', region: 'Afrique centrale', latitude: -0.7, longitude: 11.6 },
  { code: 'GM', gdeltCode: 'GA', name: 'Gambie', region: 'Afrique de l’Ouest', latitude: 13.5, longitude: -16.6 },
  { code: 'GH', gdeltCode: 'GH', name: 'Ghana', region: 'Afrique de l’Ouest', latitude: 7.9, longitude: -1.0 },
  { code: 'GN', gdeltCode: 'GV', name: 'Guinée', region: 'Afrique de l’Ouest', latitude: 10.4, longitude: -10.8 },
  { code: 'GW', gdeltCode: 'PU', name: 'Guinée-Bissau', region: 'Afrique de l’Ouest', latitude: 11.8, longitude: -15.6 },
  { code: 'KE', gdeltCode: 'KE', name: 'Kenya', region: 'Afrique de l’Est', latitude: 0.2, longitude: 37.9 },
  { code: 'LS', gdeltCode: 'LT', name: 'Lesotho', region: 'Afrique australe', latitude: -29.6, longitude: 28.2 },
  { code: 'LR', gdeltCode: 'LI', name: 'Libéria', region: 'Afrique de l’Ouest', latitude: 6.4, longitude: -9.4 },
  { code: 'LY', gdeltCode: 'LY', name: 'Libye', region: 'Afrique du Nord', latitude: 27.0, longitude: 18.0 },
  { code: 'MG', gdeltCode: 'MA', name: 'Madagascar', region: 'Afrique de l’Est', latitude: -19.0, longitude: 46.7 },
  { code: 'MW', gdeltCode: 'MI', name: 'Malawi', region: 'Afrique australe', latitude: -13.9, longitude: 33.8 },
  { code: 'ML', gdeltCode: 'ML', name: 'Mali', region: 'Afrique de l’Ouest', latitude: 17.0, longitude: -3.5 },
  { code: 'MR', gdeltCode: 'MR', name: 'Mauritanie', region: 'Afrique de l’Ouest', latitude: 20.3, longitude: -10.3 },
  { code: 'MU', gdeltCode: 'MP', name: 'Maurice', region: 'Afrique de l’Est', latitude: -20.2, longitude: 57.5 },
  { code: 'MA', gdeltCode: 'MO', name: 'Maroc', region: 'Afrique du Nord', latitude: 31.8, longitude: -7.1 },
  { code: 'MZ', gdeltCode: 'MZ', name: 'Mozambique', region: 'Afrique australe', latitude: -18.7, longitude: 35.5 },
  { code: 'NA', gdeltCode: 'WA', name: 'Namibie', region: 'Afrique australe', latitude: -22.6, longitude: 17.1 },
  { code: 'NE', gdeltCode: 'NG', name: 'Niger', region: 'Afrique de l’Ouest', latitude: 17.6, longitude: 8.1 },
  { code: 'NG', gdeltCode: 'NI', name: 'Nigéria', region: 'Afrique de l’Ouest', latitude: 9.1, longitude: 8.7 },
  { code: 'RW', gdeltCode: 'RW', name: 'Rwanda', region: 'Afrique de l’Est', latitude: -1.9, longitude: 29.9 },
  { code: 'ST', gdeltCode: 'TP', name: 'São Tomé-et-Principe', region: 'Afrique centrale', latitude: 0.3, longitude: 6.7 },
  { code: 'SN', gdeltCode: 'SG', name: 'Sénégal', region: 'Afrique de l’Ouest', latitude: 14.7, longitude: -17.4 },
  { code: 'SC', gdeltCode: 'SE', name: 'Seychelles', region: 'Afrique de l’Est', latitude: -4.6, longitude: 55.5 },
  { code: 'SL', gdeltCode: 'SL', name: 'Sierra Leone', region: 'Afrique de l’Ouest', latitude: 8.5, longitude: -11.8 },
  { code: 'SO', gdeltCode: 'SO', name: 'Somalie', region: 'Afrique de l’Est', latitude: 5.2, longitude: 46.2 },
  { code: 'ZA', gdeltCode: 'SF', name: 'Afrique du Sud', region: 'Afrique australe', latitude: -29.0, longitude: 24.0 },
  { code: 'SS', gdeltCode: 'OD', name: 'Soudan du Sud', region: 'Afrique de l’Est', latitude: 7.0, longitude: 30.0 },
  { code: 'SD', gdeltCode: 'SU', name: 'Soudan', region: 'Afrique de l’Est', latitude: 15.0, longitude: 30.0 },
  { code: 'TZ', gdeltCode: 'TZ', name: 'Tanzanie', region: 'Afrique de l’Est', latitude: -6.2, longitude: 35.7 },
  { code: 'TG', gdeltCode: 'TO', name: 'Togo', region: 'Afrique de l’Ouest', latitude: 8.6, longitude: 0.8 },
  { code: 'TN', gdeltCode: 'TS', name: 'Tunisie', region: 'Afrique du Nord', latitude: 34.0, longitude: 9.5 },
  { code: 'UG', gdeltCode: 'UG', name: 'Ouganda', region: 'Afrique de l’Est', latitude: 1.4, longitude: 32.3 },
  { code: 'ZM', gdeltCode: 'ZA', name: 'Zambie', region: 'Afrique australe', latitude: -13.1, longitude: 27.8 },
  { code: 'ZW', gdeltCode: 'ZI', name: 'Zimbabwe', region: 'Afrique australe', latitude: -19.0, longitude: 29.9 },
  { code: 'EH', gdeltCode: 'WI', name: 'Sahara occidental', region: 'Afrique du Nord', latitude: 24.2, longitude: -12.2 },
];

export function getAfricanCountryByCode(code: string) {
  return AFRICAN_COUNTRIES.find(country => country.code === code.trim().toUpperCase());
}
