export const STREAM_FRESHNESS_TTL_DAYS = 7;
export const STREAM_FRESHNESS_TTL_HOURS = STREAM_FRESHNESS_TTL_DAYS * 24;
export const STREAM_FRESHNESS_TTL_MS =
  STREAM_FRESHNESS_TTL_HOURS * 60 * 60 * 1_000;
